version: '3'
services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/siap_app
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: nop4ssword
      JWT_SECRET: developer
      JWT_EXPIRATION: 3600  # Set the desired expiration time
    depends_on:
      - postgresql
      - minio  # Added dependency on the MinIO service

  postgresql:
    image: postgres:15.3
    container_name: postgres-container
    environment:
      POSTGRES_DB: siap_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nop4ssword
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    volumes:
      - ./minio:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: developer
      MINIO_ROOT_PASSWORD: nop4ssword
      MINIO_ACCESS_KEY: developer
      MINIO_SECRET_KEY: nop4ssword
    command: server /data --console-address :9001

#security:
#  jwt:
#    secret: developer
#    expiration: 3600