version: '3'
services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/siap_app
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: anjar94
    depends_on:
      - postgresql
  postgresql:
    image: postgres:15.3
    container_name: postgres-container
    environment:
      POSTGRES_DB: siap_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: anjar94
    ports:
      - "5432:5432"

  minio:
    image: minio/minio:latest
    volumes:
      - ./minio:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: 'developer'
      MINIO_ROOT_PASSWORD: 'nop4ssword'
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    command: minio server /data