spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/siap_app
    username: postgres
    password: anjar94
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: SIAP APP
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB  # Adjust the size as needed
      max-request-size: 10MB  # Adjust the size as needed
server:
  port: 8089

minio:
  endpoint: http://minio:9000
  port: 9000
  accessKey: developer
  secretKey: nop4ssword
  secure: true
  bucket-name: erte14
  image-size: 10485760
  file-size: 1073741824
